package http

import (
	"bytes"
	"compress/gzip"
	"errors"
	"io"
	"io/ioutil"
	"net"
	"net/http"
	"net/url"
	"reflect"
	"strconv"
	"strings"
)

var (
	maxParams = 100
)

// WSFRequest operates the http request header, data, cookie and body.
// it also contains router params and current session.
type WSFRequest struct {
	http.Request
	Context     *Context
	Sess        string //session.Store
	pnames      []string
	pvalues     []string
	data        map[interface{}]interface{}
	RequestBody []byte
	Method      string
	Controller  reflect.Type
}

// NewWSFRequest return Request generated by Context.
func NewWSFRequest() *WSFRequest {
	return &WSFRequest{
		pnames:  make([]string, 0, maxParams),
		pvalues: make([]string, 0, maxParams),
		data:    make(map[interface{}]interface{}),
	}
}

// Reset resets the Request
func (r *WSFRequest) Reset(ctx *Context) {
	r.Context = ctx
	r.Sess = ""
	r.pnames = r.pnames[:0]
	r.pvalues = r.pvalues[:0]
	r.data = nil
	r.RequestBody = []byte{}
}

// Protocol returns request protocol name, such as HTTP/1.1 .
func (r *WSFRequest) Protocol() string {
	return r.Proto
}

// URI returns full request url with query string, fragment.
func (r *WSFRequest) URI() string {
	return r.RequestURI
}

// RequestURL returns request url path (without query string, fragment).
func (r *WSFRequest) RequestURL() string {
	return r.URL.Path
}

// Site returns base site url as scheme://domain type.
func (r *WSFRequest) Site() string {
	return r.Scheme() + "://" + r.Domain()
}

// Scheme returns request scheme as "http" or "https".
func (r *WSFRequest) Scheme() string {
	if scheme := r.Header.Get("X-Forwarded-Proto"); scheme != "" {
		return scheme
	}

	if r.URL.Scheme != "" {
		return r.URL.Scheme
	}

	if r.TLS == nil {
		return "http"
	}

	return "https"
}

// Domain returns host name.
func (r *WSFRequest) Domain() string {
	if r.Host != "" {
		if hostPart, _, err := net.SplitHostPort(r.Host); err == nil {
			return hostPart
		}
		return r.Host
	}
	return "localhost"
}

// Is returns boolean of this request is on given method, such as Is("POST").
func (r *WSFRequest) Is(method string) bool {
	return r.Method == method
}

// IsGet Is this a GET method request?
func (r *WSFRequest) IsGet() bool {
	return r.Is("GET")
}

// IsPost Is this a POST method request?
func (r *WSFRequest) IsPost() bool {
	return r.Is("POST")
}

// IsHead Is this a Head method request?
func (r *WSFRequest) IsHead() bool {
	return r.Is("HEAD")
}

// IsOptions Is this a OPTIONS method request?
func (r *WSFRequest) IsOptions() bool {
	return r.Is("OPTIONS")
}

// IsPut Is this a PUT method request?
func (r *WSFRequest) IsPut() bool {
	return r.Is("PUT")
}

// IsDelete Is this a DELETE method request?
func (r *WSFRequest) IsDelete() bool {
	return r.Is("DELETE")
}

// IsPatch Is this a PATCH method request?
func (r *WSFRequest) IsPatch() bool {
	return r.Is("PATCH")
}

// IsAjax returns boolean of this request is generated by ajax.
func (r *WSFRequest) IsAjax() bool {
	return r.Header.Get("X-Requested-With") == "XMLHttpRequest"
}

// IsSecure returns boolean of this request is in https.
func (r *WSFRequest) IsSecure() bool {
	return r.Scheme() == "https"
}

// IsWebsocket returns boolean of this request is in webSocket.
func (r *WSFRequest) IsWebsocket() bool {
	return r.Header.Get("Upgrade") == "websocket"
}

// IsUpload returns boolean of whether file uploads in this request or not..
func (r *WSFRequest) IsUpload() bool {
	return strings.Contains(r.Header.Get("Content-Type"), "multipart/form-data")
}

// AcceptsHTML Checks if request accepts html response
func (r *WSFRequest) AcceptsHTML() bool {
	return acceptsHTMLRegex.MatchString(r.Header.Get("Accept"))
}

// AcceptsXML Checks if request accepts xml response
func (r *WSFRequest) AcceptsXML() bool {
	return acceptsXMLRegex.MatchString(r.Header.Get("Accept"))
}

// AcceptsJSON Checks if request accepts json response
func (r *WSFRequest) AcceptsJSON() bool {
	return acceptsJSONRegex.MatchString(r.Header.Get("Accept"))
}

// AcceptsYAML Checks if request accepts json response
func (r *WSFRequest) AcceptsYAML() bool {
	return acceptsYAMLRegex.MatchString(r.Header.Get("Accept"))
}

// IP returns request client ip.
// if in proxy, return first proxy id.
// if error, return RemoteAddr.
func (r *WSFRequest) IP() string {
	ips := r.Proxy()
	if len(ips) > 0 && ips[0] != "" {
		rip, _, err := net.SplitHostPort(ips[0])
		if err != nil {
			rip = ips[0]
		}
		return rip
	}
	if ip, _, err := net.SplitHostPort(r.RemoteAddr); err == nil {
		return ip
	}
	return r.RemoteAddr
}

// Proxy returns proxy client ips slice.
func (r *WSFRequest) Proxy() []string {
	if ips := r.Header.Get("X-Forwarded-For"); ips != "" {
		return strings.Split(ips, ",")
	}
	return []string{}
}

// Referer returns http referer header.
func (r *WSFRequest) Referer() string {
	return r.Header.Get("Referer")
}

// Refer returns http referer header.
func (r *WSFRequest) Refer() string {
	return r.Referer()
}

// SubDomains returns sub domain string.
// if aa.bb.domain.com, returns aa.bb .
func (r *WSFRequest) SubDomains() string {
	parts := strings.Split(r.Host, ".")
	if len(parts) >= 3 {
		return strings.Join(parts[:len(parts)-2], ".")
	}
	return ""
}

// Port returns request client port.
// when error or empty, return 80.
func (r *WSFRequest) Port() int {
	if _, portPart, err := net.SplitHostPort(r.Host); err == nil {
		port, _ := strconv.Atoi(portPart)
		return port
	}

	return 80
}

// ParamsLen return the length of the params
func (r *WSFRequest) ParamsLen() int {
	return len(r.pnames)
}

// Param returns router param by a given key.
func (r *WSFRequest) Param(key string) string {
	for i, v := range r.pnames {
		if v == key && i <= len(r.pvalues) {
			return r.pvalues[i]
		}
	}
	return ""
}

// Params returns the map[key]value.
func (r *WSFRequest) Params() map[string]string {
	m := make(map[string]string)
	for i, v := range r.pnames {
		if i <= len(r.pvalues) {
			m[v] = r.pvalues[i]
		}
	}
	return m
}

// SetParam will set the param with key and value
func (r *WSFRequest) SetParam(key, val string) {
	// check if already exists
	for i, v := range r.pnames {
		if v == key && i <= len(r.pvalues) {
			r.pvalues[i] = val
			return
		}
	}

	r.pvalues = append(r.pvalues, val)
	r.pnames = append(r.pnames, key)
}

// ResetParams clears any of the input's Params
// This function is used to clear parameters so they may be reset between filter
// passes.
func (r *WSFRequest) ResetParams() {
	r.pnames = r.pnames[:0]
	r.pvalues = r.pvalues[:0]
}

// Query returns input data item string by a given string.
func (r *WSFRequest) Query(key string) string {
	if val := r.Param(key); val != "" {
		return val
	}
	if r.Form == nil {
		r.ParseForm()
	}
	return r.Form.Get(key)
}

// Session returns current session item value by a given key.
// if non-existed, return nil.
func (r *WSFRequest) Session(key interface{}) interface{} {
	return nil //r.Sess.Get(key)
}

// CopyBody returns the raw request body data as bytes.
func (r *WSFRequest) CopyBody(MaxMemory int64) []byte {
	if r.Body == nil {
		return []byte{}
	}

	var requestbody []byte
	safe := &io.LimitedReader{R: r.Body, N: MaxMemory}
	if r.Header.Get("Content-Encoding") == "gzip" {
		reader, err := gzip.NewReader(safe)
		if err != nil {
			return nil
		}
		requestbody, _ = ioutil.ReadAll(reader)
	} else {
		requestbody, _ = ioutil.ReadAll(safe)
	}

	r.Body.Close()
	bf := bytes.NewBuffer(requestbody)
	r.Body = http.MaxBytesReader(r.Context.Response, ioutil.NopCloser(bf), MaxMemory)
	r.RequestBody = requestbody
	return requestbody
}

// Data return the implicit data in the input
func (r *WSFRequest) Data() map[interface{}]interface{} {
	if r.data == nil {
		r.data = make(map[interface{}]interface{})
	}

	return r.data
}

// GetData returns the stored data in this context.
func (r *WSFRequest) GetData(key interface{}) interface{} {
	if v, ok := r.data[key]; ok {
		return v
	}

	return nil
}

// SetData stores data with given key in this context.
// This data are only available in this context.
func (r *WSFRequest) SetData(key, val interface{}) {
	if r.data == nil {
		r.data = make(map[interface{}]interface{})
	}
	r.data[key] = val
}

// ParseFormOrMulitForm parseForm or parseMultiForm based on Content-type
func (r *WSFRequest) ParseFormOrMulitForm(maxMemory int64) error {
	// Parse the body depending on the content type.
	if strings.Contains(r.Header.Get("Content-Type"), "multipart/form-data") {
		if err := r.ParseMultipartForm(maxMemory); err != nil {
			return errors.New("Error parsing request body:" + err.Error())
		}
	} else if err := r.ParseForm(); err != nil {
		return errors.New("Error parsing request body:" + err.Error())
	}
	return nil
}

// Bind data from request.Form[key] to dest
func (r *WSFRequest) Bind(dest interface{}, key string) error {
	value := reflect.ValueOf(dest)
	if value.Kind() != reflect.Ptr {
		return errors.New("WSFRequest: non-pointer passed to Bind: " + key)
	}

	value = value.Elem()
	if !value.CanSet() {
		return errors.New("WSFRequest: non-settable variable passed to Bind: " + key)
	}

	typ := value.Type()
	// Get real type if dest define with interface{}.
	// e.g  var dest interface{} dest=1.0
	if value.Kind() == reflect.Interface {
		typ = value.Elem().Type()
	}

	rv := r.bind(key, typ)
	if !rv.IsValid() {
		return errors.New("beego: reflect value is empty")
	}

	value.Set(rv)
	return nil
}

func (r *WSFRequest) bind(key string, typ reflect.Type) reflect.Value {
	if r.Form == nil {
		r.ParseForm()
	}

	rv := reflect.Zero(typ)
	switch typ.Kind() {
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		val := r.Query(key)
		if len(val) == 0 {
			return rv
		}
		rv = r.bindInt(val, typ)

	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		val := r.Query(key)
		if len(val) == 0 {
			return rv
		}
		rv = r.bindUint(val, typ)

	case reflect.Float32, reflect.Float64:
		val := r.Query(key)
		if len(val) == 0 {
			return rv
		}
		rv = r.bindFloat(val, typ)

	case reflect.String:
		val := r.Query(key)
		if len(val) == 0 {
			return rv
		}
		rv = r.bindString(val, typ)

	case reflect.Bool:
		val := r.Query(key)
		if len(val) == 0 {
			return rv
		}
		rv = r.bindBool(val, typ)

	case reflect.Slice:
		rv = r.bindSlice(&r.Form, key, typ)

	case reflect.Struct:
		rv = r.bindStruct(&r.Form, key, typ)

	case reflect.Ptr:
		rv = r.bindPoint(key, typ)

	case reflect.Map:
		rv = r.bindMap(&r.Form, key, typ)
	}

	return rv
}

func (r *WSFRequest) bindValue(val string, typ reflect.Type) reflect.Value {
	rv := reflect.Zero(typ)
	switch typ.Kind() {
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		rv = r.bindInt(val, typ)

	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		rv = r.bindUint(val, typ)

	case reflect.Float32, reflect.Float64:
		rv = r.bindFloat(val, typ)

	case reflect.String:
		rv = r.bindString(val, typ)

	case reflect.Bool:
		rv = r.bindBool(val, typ)

	case reflect.Slice:
		rv = r.bindSlice(&url.Values{"": {val}}, "", typ)

	case reflect.Struct:
		rv = r.bindStruct(&url.Values{"": {val}}, "", typ)

	case reflect.Ptr:
		rv = r.bindPoint(val, typ)

	case reflect.Map:
		rv = r.bindMap(&url.Values{"": {val}}, "", typ)
	}

	return rv
}

func (r *WSFRequest) bindInt(val string, typ reflect.Type) reflect.Value {
	intValue, err := strconv.ParseInt(val, 10, 64)
	if err != nil {
		return reflect.Zero(typ)
	}

	pValue := reflect.New(typ)
	pValue.Elem().SetInt(intValue)
	return pValue.Elem()
}

func (r *WSFRequest) bindUint(val string, typ reflect.Type) reflect.Value {
	uintValue, err := strconv.ParseUint(val, 10, 64)
	if err != nil {
		return reflect.Zero(typ)
	}

	pValue := reflect.New(typ)
	pValue.Elem().SetUint(uintValue)
	return pValue.Elem()
}

func (r *WSFRequest) bindFloat(val string, typ reflect.Type) reflect.Value {
	floatValue, err := strconv.ParseFloat(val, 64)
	if err != nil {
		return reflect.Zero(typ)
	}

	pValue := reflect.New(typ)
	pValue.Elem().SetFloat(floatValue)
	return pValue.Elem()
}

func (r *WSFRequest) bindString(val string, typ reflect.Type) reflect.Value {
	return reflect.ValueOf(val)
}

func (r *WSFRequest) bindBool(val string, typ reflect.Type) reflect.Value {
	val = strings.TrimSpace(strings.ToLower(val))
	switch val {
	case "true", "on", "1":
		return reflect.ValueOf(true)
	}

	return reflect.ValueOf(false)
}

type sliceValue struct {
	index int           // Index extracted from brackets.  If -1, no index was provided.
	value reflect.Value // the bound value for this slice element.
}

func (r *WSFRequest) bindSlice(params *url.Values, key string, typ reflect.Type) reflect.Value {
	maxIndex := -1
	numNoIndex := 0
	sliceValues := []sliceValue{}
	for reqKey, vals := range *params {
		if !strings.HasPrefix(reqKey, key+"[") {
			continue
		}

		// Extract the index, and the index where a sub-key starts. (e.g. field[0].subkey)
		index := -1
		leftBracket, rightBracket := len(key), strings.Index(reqKey[len(key):], "]")+len(key)
		if rightBracket > leftBracket+1 {
			index, _ = strconv.Atoi(reqKey[leftBracket+1 : rightBracket])
		}
		subKeyIndex := rightBracket + 1

		// Handle the indexed case.
		if index > -1 {
			if index > maxIndex {
				maxIndex = index
			}

			sliceValues = append(sliceValues, sliceValue{
				index: index,
				value: r.bind(reqKey[:subKeyIndex], typ.Elem()),
			})
			continue
		}

		// It's an un-indexed element.  (e.g. element[])
		numNoIndex += len(vals)
		for _, val := range vals {
			// Unindexed values can only be direct-bound.
			sliceValues = append(sliceValues, sliceValue{
				index: -1,
				value: r.bindValue(val, typ.Elem()),
			})
		}
	}
	resultArray := reflect.MakeSlice(typ, maxIndex+1, maxIndex+1+numNoIndex)
	for _, sv := range sliceValues {
		if sv.index != -1 {
			resultArray.Index(sv.index).Set(sv.value)
		} else {
			resultArray = reflect.Append(resultArray, sv.value)
		}
	}

	return resultArray
}

func (r *WSFRequest) bindStruct(params *url.Values, key string, typ reflect.Type) reflect.Value {
	result := reflect.New(typ).Elem()
	fieldValues := make(map[string]reflect.Value)
	for reqKey, val := range *params {
		var fieldName string
		if strings.HasPrefix(reqKey, key+".") {
			fieldName = reqKey[len(key)+1:]
		} else if strings.HasPrefix(reqKey, key+"[") && reqKey[len(reqKey)-1] == ']' {
			fieldName = reqKey[len(key)+1 : len(reqKey)-1]
		} else {
			continue
		}

		if _, ok := fieldValues[fieldName]; !ok {
			// Time to bind this field.  Get it and make sure we can set it.
			fieldValue := result.FieldByName(fieldName)
			if !fieldValue.IsValid() {
				continue
			}
			if !fieldValue.CanSet() {
				continue
			}
			boundVal := r.bindValue(val[0], fieldValue.Type())
			fieldValue.Set(boundVal)
			fieldValues[fieldName] = boundVal
		}
	}

	return result
}

func (r *WSFRequest) bindPoint(key string, typ reflect.Type) reflect.Value {
	return r.bind(key, typ.Elem()).Addr()
}

func (r *WSFRequest) bindMap(params *url.Values, key string, typ reflect.Type) reflect.Value {
	var (
		result    = reflect.MakeMap(typ)
		keyType   = typ.Key()
		valueType = typ.Elem()
	)
	for paramName, values := range *params {
		if !strings.HasPrefix(paramName, key+"[") || paramName[len(paramName)-1] != ']' {
			continue
		}

		key := paramName[len(key)+1 : len(paramName)-1]
		result.SetMapIndex(r.bindValue(key, keyType), r.bindValue(values[0], valueType))
	}
	return result
}
